"""Deterministic Python backend; never edits an existing generated file by hand."""

import json
import hashlib
from pathlib import Path

from .model import Program
from .validator import validate


VERSION = "0.2.0"
HEADER = "# GENERATED BY AXIOM.\n# DO NOT EDIT.\n# MODIFY THE AXIOM MODEL INSTEAD.\n"
MARKER = "SPEC = {}  # AXIOM_SPEC_INSERTION_POINT"


def generate(program: Program) -> str:
    validate(program)
    template = Path(__file__).with_name("runtime_template.py").read_text(encoding="utf-8")
    if template.count(MARKER) != 1:
        raise RuntimeError("Python backend template is missing its Axiom insertion point")
    canonical = json.dumps(program.document, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return HEADER + template.replace(MARKER, f"SPEC = json.loads({canonical!r})")


def write(program: Program, path: str | Path) -> dict:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    source = generate(program)
    destination.write_text(source, encoding="utf-8", newline="\n")
    ids = [program.document["application"]["id"]]
    for group in ("types", "capabilities", "state", "invariants", "behaviors", "commands", "migrations", "errors"):
        for entity in program.document.get(group, []):
            ids.append(entity["id"])
            if group == "types":
                ids.extend(field["id"] for field in entity.get("fields", []))
            if group == "behaviors":
                ids.extend(inp["id"] for inp in entity["inputs"])
                ids.extend(contract["id"] for contract in entity["guarantees"] if "id" in contract)
                ids.extend(contract["id"] for contract in entity["conditions"] if "id" in contract)
    manifest = {"compiler_version": VERSION, "model_version": program.version,
                "application_id": program.document["application"]["id"],
                "artifacts": [{"path": destination.name, "sha256": hashlib.sha256(source.encode("utf-8")).hexdigest(),
                               "entity_ids": sorted(ids)}]}
    destination.with_suffix(".manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n")
    return manifest
